name: Auto-tag Latest Version

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  tag-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update latest tag
        run: |
          # Update 'latest' tag to always point to main branch (development)
          git tag -f latest
          git push origin latest --force
          echo "✓ Updated 'latest' tag to point to main branch (development)"

      - name: Note about stable releases
        run: |
          echo "ℹ️  Stable releases are maintainer-controlled"
          echo "   To create a stable release:"
          echo "   1. git tag v1.0.0"
          echo "   2. git tag stable -f"
          echo "   3. git push origin v1.0.0 stable"
          echo "   This ensures stable is only updated when ready"
