name: Merge and Release

on:
  push:
    branches: [main]
    paths-ignore:
      - '*.md'
      - '.github/graphics/**'
      - '!.github/workflows/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions: {}

jobs:
  semantic-release:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Conventional Changelog Update
        uses: TriPSs/conventional-changelog-action@67139193614f5b9e8db87da1bd4240922b34d765 # v6
        id: changelog
        continue-on-error: true
        with:
          github-token: ${{ github.token }}
          output-file: 'CHANGELOG.md'
          skip-version-file: 'true'
          skip-commit: 'true'
          skip-on-empty: 'true'
          git-push: 'false'

      - name: Create Git Tag
        if: steps.changelog.outputs.version != ''
        run: |
          set -e
          echo "Creating tag: ${{ steps.changelog.outputs.tag }}"

          # Configure git
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # Create tag
          git tag ${{ steps.changelog.outputs.tag }}
          echo "✅ Tag created locally: ${{ steps.changelog.outputs.tag }}"

          # Push tag with error handling
          if git push origin ${{ steps.changelog.outputs.tag }}; then
            echo "✅ Tag pushed successfully: ${{ steps.changelog.outputs.tag }}"
          else
            echo "❌ Failed to push tag: ${{ steps.changelog.outputs.tag }}"
            echo "Check GITHUB_TOKEN permissions for contents:write"
            exit 1
          fi

      - name: Create Release
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8 # v2
        if: steps.changelog.outputs.version != ''
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          token: ${{ github.token }}
          tag_name: ${{ steps.changelog.outputs.tag }}
          name: ${{ steps.changelog.outputs.tag }}
          body: |
            ## Renovate Config Release

            ${{ steps.changelog.outputs.clean_changelog }}

            ### Usage
            Teams can now use:
            ```json
            {
              "extends": ["github>bcgov/renovate-config#${{ steps.changelog.outputs.tag }}"]
            }
            ```

            ### Migration for Existing Teams
            If you're using the main branch, consider upgrading to versioned configs:
            ```json
            {
              "extends": ["github>bcgov/renovate-config#v1"]
            }
            ```
            Benefits: stable updates, automatic upgrades, no breaking changes.

      - name: Create Major/Minor Version Tags
        if: steps.changelog.outputs.version != ''
        run: |
          set -e
          # Get the version that was just created
          VERSION="${{ steps.changelog.outputs.tag }}"
          echo "Creating major/minor tags for version: $VERSION"

          # Extract major and minor versions
          VERSION_NUM=${VERSION#v}
          MAJOR_VERSION="v${VERSION_NUM%%.*}"
          MINOR_VERSION="v${VERSION_NUM%.*}"

          echo "Major version: $MAJOR_VERSION"
          echo "Minor version: $MINOR_VERSION"

          # Create/update major version tag (e.g., v1)
          git tag -f $MAJOR_VERSION
          if git push origin $MAJOR_VERSION --force; then
            echo "✅ Updated $MAJOR_VERSION tag"
          else
            echo "❌ Failed to push $MAJOR_VERSION tag"
            exit 1
          fi

          # Create/update minor version tag (e.g., v1.1)
          git tag -f $MINOR_VERSION
          if git push origin $MINOR_VERSION --force; then
            echo "✅ Updated $MINOR_VERSION tag"
          else
            echo "❌ Failed to push $MINOR_VERSION tag"
            exit 1
          fi

          echo "🎉 All version tags created: $VERSION, $MINOR_VERSION, $MAJOR_VERSION"
