name: PR Validate

on:
  pull_request:
    types: [edited, opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-edit-${{ github.event.number }}
  cancel-in-progress: true

permissions:
  pull-requests: write

jobs:
  validate:
    name: Validate PR
    if: (! github.event.pull_request.draft)
    uses: bcgov/quickstart-openshift-helpers/.github/workflows/.pr-validate.yml@ca6579bdadf383a2513397081f963889b92823a4 # v1.1.0
