name: PR Validate

on:
  pull_request:
    types: [edited, opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-edit-${{ github.event.number }}
  cancel-in-progress: true

permissions:
  pull-requests: write

jobs:
  validate:
    name: Validate PR
    if: (! github.event.pull_request.draft)
    uses: bcgov/quickstart-openshift-helpers/.github/workflows/.pr-validate.yml@18a043020cdc4f1125ec592524e8163edc767f4a # v1.2.0
